<?php
return
    [
        'is_nav'=>1,//1导航菜单；0 非导航栏
        'menu'=> [
            'href' => 'wechat',
            'title' => 'wechat',
            'status' => 1,
            'auth_verify' => 1,
            'menu_status' => 1,
            'type' => '1',
            'icon' => 'layui-icon layui-icon-login-wechat',
            'menulist' => [
                [
                    'href' => 'backend.index',
                    'title' => '账号',
                    'status' => 1,
                    'menu_status' => 1,
                    'type'=>1,
                    'icon' => 'layui-icon layui-icon-login-wechat',
                    'menulist' => [
                        ['href' => 'backend.index/index', 'title' => 'index', 'status' => 1,
                            'menu_status' => 0,],
                        ['href' => 'backend.index/edit', 'title' => 'edit', 'status' => 1,
                            'menu_status' => 0,],
                        ['href' => 'backend.index/modify', 'title' => 'modify', 'status' => 1,
                            'menu_status' => 0,],
                    ]
                ],
                [
                    'href' => 'backend.menu',
                    'title' => '菜单',
                    'status' => 1,
                    'menu_status' => 1,
                    'type' => '1',
                    'icon' => 'layui-icon layui-icon-login-wechat',
                    'menulist' => [
                        ['href' => 'backend.menu/index', 'title' => 'index', 'status' => 1,
                            'menu_status' => 0,],
                        ['href' => 'backend.menu/add', 'title' => 'add', 'status' => 1,
                            'menu_status' => 0,],
                        ['href' => 'backend.menu/edit', 'title' => 'edit', 'status' => 1,
                            'menu_status' => 0,],
                        ['href' => 'backend.menu/modify', 'title' => 'modify', 'status' => 1,
                            'menu_status' => 0,],
                    ]
                ],
                [
                    'href' => 'backend.fans',
                    'title' => '粉丝',
                    'status' => 1,
                    'menu_status' => 1,
                    'type' => '1',
                    'icon' => 'layui-icon layui-icon-login-wechat',
                    'menulist' => [
                        ['href' => 'backend.fans/index', 'title' => 'list', 'status' => 1,'menu_status' => 0,],
                        ['href' => 'backend.fans/aysn', 'title' => 'aysn', 'status' => 1,'menu_status' => 0,],
                        ['href' => 'backend.fans/edit', 'title' => 'edit', 'status' => 1,'menu_status' => 0,],
                    ]
                ],
                [
                    'href' => 'backend.tags',
                    'title' => '标签',
                    'status' => 1,
                    'menu_status' => 1,
                    'type' => '1',
                    'icon' => 'layui-icon layui-icon-login-wechat',
                    'menulist' => [
                        ['href' => 'backend.tags/index', 'title' => 'index', 'status' => 1,
                            'menu_status' => 0,],
                        ['href' => 'backend.tags/add', 'title' => 'add', 'status' => 1,
                            'menu_status' => 0,],
                        ['href' => 'backend.tags/edit', 'title' => 'edit', 'status' => 1,
                            'menu_status' => 0,],
                        ['href' => 'backend.tags/delete', 'title' => 'delete', 'status' => 1,
                            'menu_status' => 0,],
                        ['href' => 'backend.tags/destroy', 'title' => 'destroy', 'status' => 1,
                            'menu_status' => 0,],
                        ['href' => 'backend.tags/modify', 'title' => 'modify', 'status' => 1,
                            'menu_status' => 0,],
                        ['href' => 'backend.tags/aysn', 'title' => 'aysn', 'status' => 1,
                            'menu_status' => 0,],
                        ['href' => 'backend.tags/recycle', 'title' => 'recycle', 'status' => 1,
                            'menu_status' => 0,],
                        ['href' => 'backend.tags/restore', 'title' => 'restore', 'status' => 1,
                            'menu_status' => 0,],
                    ]
                ],
                [
                    'href' => 'backend.message',
                    'title' => '消息',
                    'status' => 1,
                    'menu_status' => 1,
                    'type' => '1',
                    'icon' => 'layui-icon layui-icon-login-wechat',
                    'menulist' => [
                        ['href' => 'backend.index/message/index', 'title' => 'index', 'status' => 1,
                            'menu_status' => 0,],
                        ['href' => 'backend.index/message/delete', 'title' => 'delete', 'status' => 1,
                            'menu_status' => 0,],
                        ['href' => 'backend.index/message/reply', 'title' => 'reply', 'status' => 1,
                            'menu_status' => 0,],
                    ]
                ],
                [
                    'href' => 'backend.material',
                    'title' => '素材',
                    'status' => 1,
                    'menu_status' => 1,
                    'type'=>1,
                    'icon' => 'layui-icon layui-icon-login-wechat',
                    'menulist' => [
                        ['href' => 'backend.material/index', 'title' => 'list', 'status' => 1,
                            'menu_status' => 0,],
                        ['href' => 'backend.material/add', 'title' => 'add', 'status' => 1,
                            'menu_status' => 0,],
                        ['href' => 'backend.material/edit', 'title' => 'edit', 'status' => 1,
                            'menu_status' => 0,],
                        ['href' => 'backend.material/aysn', 'title' => 'aysn', 'status' => 1,
                            'menu_status' => 0,],
                        ['href' => 'backend.material/delete', 'title' => 'delete', 'status' => 1,
                            'menu_status' => 0,],
                        ['href' => 'backend.material/send', 'title' => 'send', 'status' => 1,
                            'menu_status' => 0,],
                        ['href' => 'backend.material/preview', 'title' => 'preview', 'status' => 1,
                            'menu_status' => 0,],
                        ['href' => 'backend.material/getListImage', 'title' => 'imagelist', 'status' => 1,
                            'menu_status' => 0,],
                        ['href' => 'backend.material/imageUpload', 'title' => 'imageUpload', 'status' => 1,
                            'menu_status' => 0,],
                        ['href' => 'backend.material/videoUpload', 'title' => 'videoUpload', 'status' => 1,
                            'menu_status' => 0,],
                        ['href' => 'backend.material/voiceUpload', 'title' => 'voiceUpload', 'status' => 1,
                            'menu_status' => 0,],
                        ['href' => 'backend.material/thumbUpload', 'title' => 'thumbUpload', 'status' => 1,
                            'menu_status' => 0,],
                    ]
                ],
                [
                    'href' => 'backend.qrcode',
                    'title' => '二维码',
                    'status' => 1,
                    'menu_status' => 1,
                    'type'=>1,
                    'icon' => 'layui-icon layui-icon-login-wechat',
                    'menulist' => [
                        ['href' => 'backend.qrcode/index', 'title' => 'list', 'status' => 1,
                            'menu_status' => 0,],
                        ['href' => 'backend.qrcode/add', 'title' => 'add', 'status' => 1,
                            'menu_status' => 0,],
                        ['href' => 'backend.qrcode/edit', 'title' => 'edit', 'status' => 1,
                            'menu_status' => 0,],
                        ['href' => 'backend.qrcode/delete', 'title' => 'delete', 'status' => 1,
                            'menu_status' => 0,],
                        ['href' => 'backend.qrcode/modify', 'title' => 'modify', 'status' => 1,
                            'menu_status' => 0,],
                    ]
                ],
                [
                    'href' => 'backend.reply',
                    'title' => '自动回复',
                    'status' => 1,
                    'menu_status' => 1,
                    'type'=>1,
                    'icon' => 'layui-icon layui-icon-login-wechat',
                    'menulist' => [
                        ['href' => 'backend.reply/index', 'title' => 'list', 'status' => 1,
                            'menu_status' => 0,],
                        ['href' => 'backend.reply/add', 'title' => 'add', 'status' => 1,
                            'menu_status' => 0,],
                        ['href' => 'backend.reply/edit', 'title' => 'edit', 'status' => 1,
                            'menu_status' => 0,],
                        ['href' => 'backend.reply/delete', 'title' => 'delete', 'status' => 1,
                            'menu_status' => 0,],
                        ['href' => 'backend.reply/modify', 'title' => 'modify', 'status' => 1,
                            'menu_status' => 0,],
                    ]
                ],
            ]
        ]
    ];