<?php
/**
 * funadmin
 * ============================================================================
 * 版权所有 2018-2027 funadmin，并保留所有权利。
 * 网站地址: https://www.funadmin.com
 * ----------------------------------------------------------------------------
 * 采用最新Thinkphp6实现
 * ============================================================================
 * Author: yuege
 * Date: 2019/9/4
 */

declare (strict_types=1);

namespace app\wechat\controller\backend;

use think\Request;
use think\App;
use think\facade\View;
use app\common\annotation\NodeAnnotation;
use app\common\annotation\ControllerAnnotation;
use app\wechat\model\WechatAccount;
use fun\helper\DataHelper;
use app\wechat\model\WechatMaterialInfo;
use app\wechat\model\WechatMaterial;

/**
 * @ControllerAnnotation ('Index')
 */
class Index extends WxBase
{
    protected $pageSize = 15;

    public function __construct(App $app)
    {
        parent::__construct($app); // TODO: Change the autogenerated
        $this->modelClass = new WechatAccount();
        View::assign('statusList', $this->modelClass->getStatusList());
        View::assign('typeList', $this->modelClass->getTypeList());

    }
}